# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       libdres

# >> macros
# << macros

Summary:    Dependency resolver for OHM
Version:    1.1.12
Release:    1
Group:      System/Resource Policy
License:    LGPLv2.1
URL:        http://meego.gitorious.org/maemo-multimedia/dres
Source0:    %{name}-%{version}.tar.gz
Source100:  libdres.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(ohm)
BuildRequires:  pkgconfig(libprolog)
BuildRequires:  pkgconfig(libsimple-trace)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(dbus-glib-1)
BuildRequires:  bison
BuildRequires:  flex

%description
A dependency resolver for OHM.

%package utils
Summary:    Miscallaneous DRES utilities, including dresc
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description utils
Miscallaneous DRES utilities, including dresc.

%package -n ohm-plugin-resolver
Summary:    OHM dependency resolver plugin
Group:      System/Resource Policy
Requires:   %{name} = %{version}-%{release}
Requires:   ohm

%description -n ohm-plugin-resolver
A dependency resolver plugin for OHM.

%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for %{name}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%autogen --disable-static
%configure --disable-static
make

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post

#rm -f -- $RPM_BUILD_ROOT%{_libdir}/*.la
#rm -f -- $RPM_BUILD_ROOT%{_libdir}/ohm/*.la

# << install post


%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/*.so.*
%doc README COPYING INSTALL AUTHORS NEWS ChangeLog
# << files

%files utils
%defattr(-,root,root,-)
# >> files utils
%{_bindir}/dresc
# << files utils

%files -n ohm-plugin-resolver
%defattr(-,root,root,-)
# >> files ohm-plugin-resolver
%{_libdir}/ohm/libohm_dres.so
%config %{_sysconfdir}/ohm/plugins.d/dres.ini
# << files ohm-plugin-resolver

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/dres
%{_libdir}/*.so
%{_libdir}/pkgconfig/*
# << files devel
